config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views import defaults as default_views
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.authtoken.views import obtain_auth_token

from pemors.core.views import about_view
from pemors.titles.views import home_view

urlpatterns = [
    path(settings.ADMIN_URL, admin.site.urls),
    path("__reload__/", include("django_browser_reload.urls")),
    path("", home_view, name="home"),
    path("about/", about_view, name="about"),
    path("accounts/", include("allauth.urls")),
    path("users/", include("pemors.users.urls", namespace="users")),
    path("titles/", include("pemors.titles.urls", namespace="titles")),
    path("api/titles/", include("pemors.titles.api.urls", namespace="titles_api")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# API URLS
urlpatterns += [
    # API base url
    path("api/", include("config.api_router")),
    # DRF auth token
    path("auth-token/", obtain_auth_token),
    path("api/schema/", SpectacularAPIView.as_view(), name="api-schema"),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="api-schema"),
        name="api-docs",
    ),
]

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
if "debug_toolbar" in settings.INSTALLED_APPS:
    import debug_toolbar

    urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pemors/titles/api/urls.py
from django.urls import include, path
from rest_framework.routers import DefaultRouter

from pemors.titles.api.views import (
    UserRatingViewSet,
    progress_view,
    recommendation_view,
    title_view,
)

router = DefaultRouter()
router.register(r"user_rating", UserRatingViewSet, basename="user_rating")
urlpatterns = [
    path("", include(router.urls)),
    path("recommend", recommendation_view, name="recommend"),
    path("progress", progress_view, name="progress"),
    path("<str:pk>", title_view, name="title_detail"),
]
app_name = "titles_api"

pemors/titles/urls.py
from django.urls import path

from pemors.titles.views import coldstart_view, title_detail_view

app_name = "titles"
urlpatterns = [
    path("coldstart", view=coldstart_view, name="coldstart"),
    path("<str:id>", view=title_detail_view, name="title"),
]

pemors/users/urls.py
from django.urls import path

from pemors.users.views import user_detail_view, user_personality_view

app_name = "users"
urlpatterns = [
    path("me/", view=user_detail_view, name="detail"),
    path("personality", view=user_personality_view, name="personality"),
]

pemors/users/forms.py
from allauth.account.forms import SignupForm
from allauth.socialaccount.forms import SignupForm as SocialSignupForm
from django import forms
from django.contrib.auth import forms as admin_forms
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()

QUESTIONS = [
    {"question": _("Am the life of the party."), "type": 1, "math": "+"},
    {"question": _("Feel little concern for others."), "type": 2, "math": "-"},
    {"question": _("Am always prepared."), "type": 3, "math": "+"},
    {"question": _("Get stressed out easily."), "type": 4, "math": "-"},
    {"question": _("Have a rich vocabulary."), "type": 5, "math": "+"},
    {"question": _("Don't talk a lot."), "type": 1, "math": "-"},
    {"question": _("Am interested in people."), "type": 2, "math": "+"},
    {"question": _("Leave my belongings around."), "type": 3, "math": "-"},
    {"question": _("Am relaxed most of the time."), "type": 4, "math": "+"},
    {
        "question": _("Have difficulty understanding abstract ideas."),
        "type": 5,
        "math": "-",
    },
    {"question": _("Feel comfortable around people."), "type": 1, "math": "+"},
    {"question": _("Insult people."), "type": 2, "math": "-"},
    {"question": _("Pay attention to details."), "type": 3, "math": "+"},
    {"question": _("Worry about things."), "type": 4, "math": "-"},
    {"question": _("Have a vivid imagination."), "type": 5, "math": "+"},
    {"question": _("Keep in the background."), "type": 1, "math": "-"},
    {"question": _("Sympathize with others' feelings."), "type": 2, "math": "+"},
    {"question": _("Make a mess of things."), "type": 3, "math": "-"},
    {"question": _("Seldom feel blue."), "type": 4, "math": "+"},
    {"question": _("Am not interested in abstract ideas."), "type": 5, "math": "-"},
    {"question": _("Start conversations."), "type": 1, "math": "+"},
    {
        "question": _("Am not interested in other people's problems."),
        "type": 2,
        "math": "-",
    },
    {"question": _("Get chores done right away."), "type": 3, "math": "+"},
    {"question": _("Am easily disturbed."), "type": 4, "math": "-"},
    {"question": _("Have excellent ideas."), "type": 5, "math": "+"},
    {"question": _("Have little to say."), "type": 1, "math": "-"},
    {"question": _("Have a soft heart."), "type": 2, "math": "+"},
    {
        "question": _("Often forget to put things back in their proper place."),
        "type": 3,
        "math": "-",
    },
    {"question": _("Get upset easily."), "type": 4, "math": "-"},
    {"question": _("Do not have a good imagination."), "type": 5, "math": "-"},
    {
        "question": _("Talk to a lot of different people at parties."),
        "type": 1,
        "math": "+",
    },
    {"question": _("Am not really interested in others."), "type": 2, "math": "-"},
    {"question": _("Like order."), "type": 3, "math": "+"},
    {"question": _("Change my mood a lot."), "type": 4, "math": "-"},
    {"question": _("Am quick to understand things."), "type": 5, "math": "+"},
    {"question": _("Don't like to draw attention to myself."), "type": 1, "math": "-"},
    {"question": _("Take time out for others."), "type": 2, "math": "+"},
    {"question": _("Shirk my duties."), "type": 3, "math": "-"},
    {"question": _("Have frequent mood swings."), "type": 4, "math": "-"},
    {"question": _("Use difficult words."), "type": 5, "math": "+"},
    {
        "question": _("Don't mind being the center of attention."),
        "type": 1,
        "math": "+",
    },
    {"question": _("Feel others' emotions."), "type": 2, "math": "+"},
    {"question": _("Follow a schedule."), "type": 3, "math": "+"},
    {"question": _("Get irritated easily."), "type": 4, "math": "-"},
    {"question": _("Spend time reflecting on things."), "type": 5, "math": "+"},
    {"question": _("Am quiet around strangers."), "type": 1, "math": "-"},
    {"question": _("Make people feel at ease."), "type": 2, "math": "+"},
    {"question": _("Am exacting in my work."), "type": 3, "math": "+"},
    {"question": _("Often feel blue."), "type": 4, "math": "-"},
    {"question": _("Am full of ideas."), "type": 5, "math": "+"},
]


class UserAdminChangeForm(admin_forms.UserChangeForm):
    class Meta(admin_forms.UserChangeForm.Meta):
        model = User


class UserAdminCreationForm(admin_forms.UserCreationForm):
    """
    Form for User Creation in the Admin Area.
    To change user signup, see UserSignupForm and UserSocialSignupForm.
    """

    class Meta(admin_forms.UserCreationForm.Meta):
        model = User

        error_messages = {
            "username": {"unique": _("This username has already been taken.")}
        }


class UserSignupForm(SignupForm):
    """
    Form that will be rendered on a user sign up section/screen.
    Default fields will be added automatically.
    Check UserSocialSignupForm for accounts created from social.
    """


class UserSocialSignupForm(SocialSignupForm):
    """
    Renders the form when user has signed up using social accounts.
    Default fields will be added automatically.
    See UserSignupForm otherwise.
    """


class UserPersonalityForm(forms.Form):
    CHOICES = [(1, ""), (2, ""), (3, ""), (4, ""), (5, "")]
    WIDGET = forms.RadioSelect(attrs={"class": "input_question"})

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for i, question in enumerate(QUESTIONS):
            self.fields[f"question_{i}"] = forms.ChoiceField(
                choices=self.CHOICES,
                label=question["question"],
                widget=self.WIDGET,
                initial=(3, ""),
            )

pemors/core/views.py
from django.views.generic import TemplateView


class AboutView(TemplateView):
    template_name = "pages/about.html"


about_view = AboutView.as_view()

pemors/titles/api/views.py
import logging

import surprise
from django.core.cache import cache
from django.http import JsonResponse
from rest_framework import viewsets
from rest_framework.generics import RetrieveAPIView
from rest_framework.permissions import IsAuthenticated
from rest_framework.views import APIView

from pemors.titles.api.serializers import TitleSerializer, UserRatingSerializer
from pemors.titles.models import Title, UserRating, UserTasks
from pemors.titles.recommender import RECOMMENDATION_CACHE_FORMAT, Recommender

logger = logging.getLogger(__name__)


class UserRatingViewSet(viewsets.ModelViewSet):
    serializer_class = UserRatingSerializer
    queryset = UserRating.objects.all()


class RecommendationView(APIView):
    permission_classes = []
    movie_recommender = Recommender(algo=surprise.SVD)
    PAGE_SIZE = 30

    def get(self, request):
        page = request.GET.get("page")
        page = int(page) if page else 0
        i = page * self.PAGE_SIZE
        j = (page + 1) * self.PAGE_SIZE
        data = {
            "movies": cache.get(RECOMMENDATION_CACHE_FORMAT.format(request.user.id))[
                i:j
            ],
        }
        return JsonResponse(status=200, data=data)


recommendation_view = RecommendationView.as_view()


class ProgressAPI(APIView):
    permission_classes = [IsAuthenticated]

    def get(self, request):
        data = {}
        query = UserTasks.objects.filter(user=request.user)
        if query.exists():
            data["status"] = query[0].task_result.status
        else:
            data["status"] = "Not found"
        return JsonResponse(status=200, data=data)


progress_view = ProgressAPI.as_view()


class TitleAPIView(RetrieveAPIView):
    queryset = Title.objects.all()
    serializer_class = TitleSerializer


title_view = TitleAPIView.as_view()

pemors/titles/views.py
import logging
import random

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Count
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_page
from django.views.generic import DetailView, TemplateView

from pemors.titles.api.serializers import TitleSerializer
from pemors.titles.models import Title, UserRating
from pemors.titles.tasks import recalculate_recommendations_for_user_task

logger = logging.getLogger(__name__)


@method_decorator(cache_page(0), name="dispatch")
class TitleDetailView(LoginRequiredMixin, DetailView):
    model = Title
    slug_field = "id"
    slug_url_kwarg = "id"
    context_object_name = "title"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        _filter = {"user": self.request.user, "title": context_data["title"]}
        context_data["rating"] = UserRating.objects.filter(**_filter).first()
        context_data["title_data"] = TitleSerializer(
            instance=context_data["title"]
        ).data
        return context_data


class ColdStart(LoginRequiredMixin, TemplateView):
    template_name = "titles/coldstart.html"

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        logger.info(f"Generating most rated movie list for user {self.request.user}")

        title_counter = list(
            UserRating.objects.values("title_id")
            .annotate(total=Count("title_id"))
            .filter(total__gte=100)
            .values("title_id", "total")
        )
        title_counter = sorted(title_counter, key=lambda d: d["total"], reverse=True)
        ratings = UserRating.objects.filter(user=self.request.user).values_list(
            "title_id", flat=True
        )
        titles = [
            title["title_id"]
            for title in title_counter
            if title["title_id"] not in ratings
        ]
        titles = random.choices(titles, k=200)
        random_items = Title.objects.filter(id__in=titles).select_related("rating")
        context_data["movies"] = TitleSerializer(random_items, many=True).data
        random.shuffle(context_data["movies"])
        context_data["needed_movies"] = settings.NEEDED_MOVIES
        return context_data

    def dispatch(self, *args, **kwargs):
        if self.request.user.rating_counter >= settings.NEEDED_MOVIES:
            return redirect(reverse("home"))
        return super().dispatch(*args, **kwargs)


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "pages/home.html"

    def get_context_data(self, **kwargs):
        if not self.request.user.is_updated:
            recalculate_recommendations_for_user_task.delay(self.request.user.id)
        else:
            logger.info(f"Skipping recalculation for user {self.request.user.email}")
        return super().get_context_data(**kwargs)


home_view = HomeView.as_view()

title_detail_view = TitleDetailView.as_view()

coldstart_view = ColdStart.as_view()

pemors/users/api/views.py
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.decorators import action
from rest_framework.mixins import ListModelMixin, RetrieveModelMixin, UpdateModelMixin
from rest_framework.response import Response
from rest_framework.viewsets import GenericViewSet

from .serializers import UserSerializer

User = get_user_model()


class UserViewSet(RetrieveModelMixin, ListModelMixin, UpdateModelMixin, GenericViewSet):
    serializer_class = UserSerializer
    queryset = User.objects.all()
    lookup_field = "username"

    def get_queryset(self, *args, **kwargs):
        assert isinstance(self.request.user.id, int)
        return self.queryset.filter(id=self.request.user.id)

    @action(detail=False)
    def me(self, request):
        serializer = UserSerializer(request.user, context={"request": request})
        return Response(status=status.HTTP_200_OK, data=serializer.data)

pemors/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views.generic import TemplateView

from pemors.users.forms import QUESTIONS, UserPersonalityForm
from pemors.users.models import Profile

User = get_user_model()


class UserDetailView(LoginRequiredMixin, TemplateView):
    model = User
    template_name = "users/user_detail.html"


user_detail_view = UserDetailView.as_view()


def user_personality_view(request):
    if request.method == "POST":
        data = request.POST
        form = UserPersonalityForm(data=data)
        if form.is_valid():
            calculate_user_personality_with_form(form, request.user)
            return redirect("home")
        else:
            return render(request, "users/personality.html", {"form": form})
    else:
        form = UserPersonalityForm()
    return render(request, "users/personality.html", {"form": form})


def calculate_user_personality_with_form(form, user):
    scores = [0 for _ in range(0, 5)]
    for i, questiondata in enumerate(QUESTIONS):
        answer = int(form.cleaned_data[f"question_{i}"])
        scores[int(questiondata["type"]) - 1] += (
            answer if questiondata["math"] == "+" else 5 - (answer - 1)
        )

    profile, _ = Profile.objects.get_or_create(user=user)
    profile.ext = scores[0] / 10
    profile.agr = scores[1] / 10
    profile.con = scores[2] / 10
    profile.neu = scores[3] / 10
    profile.opn = scores[4] / 10
    profile.save()

pemors/templates/users/personality.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% load i18n %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <section class="text-white body-font">
    <div class="container px-5 py-24 mx-auto">
      <div class="text-center mb-16">
        <h1 class="sm:text-3xl text-2xl font-medium text-center title-font text-white mb-4">Test de personalidad</h1>
        <p class="text-base leading-relaxed xl:w-2/4 lg:w-3/4 mx-auto">Usaremos esta información para recomendarte
                                                                       películas acordes a tu personalidad. Esta
                                                                       información no será compartida con
                                                                       terceros</p>
      </div>
      <div class="w-full max-w-3xl mx-auto">
        <form id="personality_form" method="post" action="{% url 'users:personality' %}"
              class="shadow-md rounded px-8 pt-6 pb-8 mb-4">
          {% csrf_token %}
          <div class="mb-4 flex justify-between">
            <h2
              class="font-bold title-font tracking-widest mb-4 text-base text-center sm:text-left">{% trans 'How much do you agree with' %}</h2>
            <div class="mr-2">
              <span class="number mr-1">1</span>
              <span class="number">2</span>
              <span class="number">3</span>
              <span class="number">4</span>
              <span class="number">5</span>
            </div>
          </div>
          {{ form|crispy }}
          <div class="">
            <button
              type="submit"
              class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">
              {% trans 'Predict personality' %}
            </button>
          </div>
        </form>
      </div>
    </div>
  </section>

{% endblock %}

pemors/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
  <div>
    <section class="">
      <div class="container px-5 py-24 mx-auto">
        <div class="flex flex-col text-center w-full mb-20">
          <h2 class="text-xs text-indigo-500 tracking-widest font-medium title-font mb-1"></h2>
          <h1 class="sm:text-3xl text-2xl font-medium title-font">Mi personalidad</h1>
        </div>

        <div class="flex flex-wrap -m-4 justify-center">
          <div class="p-4 md:w-1/3">
            <div class="flex rounded-lg h-full bg-gray-800 p-8 flex-col">
              <div class="flex items-center mb-3">
                <div
                  class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                       class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 class="text-lg title-font font-medium">Apertura a la experiencia:
                  <span
                    class="mt-3 text-indigo-500 inline-flex items-center">{{ user.profile.opn|floatformat }} / 5</span>
                </h2>
              </div>
              <div class="flex-grow">
                <p class="leading-relaxed text-base">Este rasgo está totalmente relacionado con la capacidad humana de
                                                     buscar nuevas experiencias en nuestra vida, así mismo también tiene
                                                     que ver con la habilidad de visualizar un futuro de forma
                                                     creativa</p>
              </div>
            </div>
          </div>

          <div class="p-4 md:w-1/3">
            <div class="flex rounded-lg h-full bg-gray-800 p-8 flex-col">
              <div class="flex items-center mb-3">
                <div
                  class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                       class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 class="text-lg title-font font-medium">Responsabilidad:
                  <span
                    class="mt-3 text-indigo-500 inline-flex items-center">{{ user.profile.con|floatformat }} / 5</span>
                </h2>
              </div>
              <div class="flex-grow">
                <p class="leading-relaxed text-base">La habilidad del autocontrol y la capacidad de diseñar métodos de
                                                     acción eficaces. Las personas que tiene un alto grado de
                                                     responsabilidad son grandes planificadores y organizadores además
                                                     de tener un fuerte compromiso con los objetivos y metas.</p>
              </div>
            </div>
          </div>

          <div class="p-4 md:w-1/3">
            <div class="flex rounded-lg h-full bg-gray-800 p-8 flex-col">
              <div class="flex items-center mb-3">
                <div
                  class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                       class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 class="text-lg title-font font-medium">Extraversión
                  <span
                    class="mt-3 text-indigo-500 inline-flex items-center">{{ user.profile.ext|floatformat }} / 5</span>
                </h2>
              </div>
              <div class="flex-grow">
                <p class="leading-relaxed text-base">La extraversión tiene que ver con el grado en el que el sujeto
                                                     está abierto con los demás, es decir, este rasgo analiza cuánto le
                                                     agrada a un sujeto estar rodeado de los demás.</p>
              </div>
            </div>
          </div>

          <div class="p-4 md:w-1/3">
            <div class="flex rounded-lg h-full bg-gray-800 p-8 flex-col">
              <div class="flex items-center mb-3">
                <div
                  class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                       class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 class="text-lg title-font font-medium">Amabilidad:
                  <span
                    class="mt-3 text-indigo-500 inline-flex items-center">{{ user.profile.agr|floatformat }} / 5</span>
                </h2>
              </div>
              <div class="flex-grow">
                <p class="leading-relaxed text-base">La amabilidad es el rasgo que muestra el grado de tolerancia y
                                                     respeto de una persona. Una persona amable será auqella que confía
                                                     en la honestidad de la palabra, su vocación es prestar la ayuda a
                                                     aquellos que lo necesiten. La humildad, la sencillez y la empatía
                                                     son los atributos básicos de las personas amables.</p>
              </div>
            </div>
          </div>

          <div class="p-4 md:w-1/3">
            <div class="flex rounded-lg h-full bg-gray-800 p-8 flex-col">
              <div class="flex items-center mb-3">
                <div
                  class="w-8 h-8 mr-3 inline-flex items-center justify-center rounded-full bg-indigo-500 flex-shrink-0">
                  <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
                       class="w-5 h-5" viewBox="0 0 24 24">
                    <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                  </svg>
                </div>
                <h2 class="text-lg title-font font-medium">Estabilidad emocional:
                  <span
                    class="mt-3 text-indigo-500 inline-flex items-center">{{ user.profile.neu|floatformat }} / 5</span>
                </h2>
              </div>
              <div class="flex-grow">
                <p class="leading-relaxed text-base">La estabilidad emocional es la resiliencia con la que una persona
                                                     afronta las situaciones problemáticas en la vida, los individuos
                                                     tranquilos no suelen sentir rabia y huyen del enfado, su estado es
                                                     animado y saben gestionar correctamente las crisis personales.</p>
              </div>
            </div>
          </div>
        </div>


      </div>
    </section>
    <div class="flex mb-16">
      <a href="/"
      class="mx-auto text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg"
      type="submit">Ver mis recomendaciones</a>
    </div>

  </div>
{% endblock content %}

pemors/templates/users/user_form.html
{% extends "base.html" %}
{% load tailwind_filters %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="">
      <div class="">
        <button type="submit" class="">Update</button>
      </div>
    </div>
  </form>
{% endblock %}